### PR TITLE
explain that it is possible for the app to ping itself

### PR DESCRIPTION
**Pull request by jjb**
feature discussed in #7 

view readme here https://github.com/jjb/deploy-hook-forker/tree/self-notification-documentation

### CODE REVIEW

**Comment by deadlyicon** [comment]
what is the use case for this? Wouldn't this cause a loop?

**Comment by jjb** [comment]
> what is the use case for this?

To notify services when the deploy-hook-forker instance is deployed, like slack 

> Wouldn't this cause a loop?

I don't think so...

1. user deploys foo-deploy-hook-forker
2. heroku pings foo-deploy-hook-forker.herokuapp.com
3. foo-deploy-hook-forker pings other services
4. fin

right?

**Comment by deadlyicon** [comment]
Ah yes. I see. I'm down with this :)

**Comment by jjb** [comment]
sweet!
 
 
On Tue, Jun 7, 2016, at 12:40 PM, Jared Grippe wrote:
> Merged #10[1].
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
>
 

Links:

  1. https://github.com/deadlyicon/deploy-hook-forker/pull/10
  2. https://github.com/deadlyicon/deploy-hook-forker/pull/10#event-684638710
  3. https://github.com/notifications/unsubscribe/AAAX0caytYoUA_9HqoEZLFtAyRZAr5daks5qJZ8HgaJpZM4IugWz

**Pull request merged**
